modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="http://github.com/itsmeow/whisperwoods/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/whisperwoods"
logoFile="whisperwoods_banner.gif"
credits="Cybercat5555: Design, Modeling, Texturing, Ideas; its_meow: Programming, AI, Functionality"
authors="cybercat5555, its_meow"
license="CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode"
[[mods]]
  modId="whisperwoods"
  version="${file.jarVersion}"
  displayName="Whisperwoods"
  description='''
Spooky forest stuff for spooky jam'''
  [[dependencies.whisperwoods]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"